#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipvsadm
Version  : 1.29
Release  : 1
URL      : https://mirrors.edge.kernel.org/pub/linux/utils/kernel/ipvsadm/ipvsadm-1.29.tar.xz
Source0  : https://mirrors.edge.kernel.org/pub/linux/utils/kernel/ipvsadm/ipvsadm-1.29.tar.xz
Summary  : Utility to administer the Linux Virtual Server
Group    : Development/Tools
License  : GPL-2.0
Requires: ipvsadm-bin
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : popt-dev

%description
ipvsadm is a utility to administer the IP Virtual Server services
offered by the latest Linux kernel 2.6.x.

%package bin
Summary: bin components for the ipvsadm package.
Group: Binaries

%description bin
bin components for the ipvsadm package.


%package doc
Summary: doc components for the ipvsadm package.
Group: Documentation

%description doc
doc components for the ipvsadm package.


%prep
%setup -q -n ipvsadm-1.29

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531164895
make

%install
export SOURCE_DATE_EPOCH=1531164895
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ipvsadm
cp debian/copyright %{buildroot}/usr/share/doc/ipvsadm/debian_copyright
%make_install

%files
%defattr(-,root,root,-)
/usr/man/man8/ipvsadm-restore.8
/usr/man/man8/ipvsadm-save.8
/usr/man/man8/ipvsadm.8

%files bin
%defattr(-,root,root,-)
/usr/bin/ipvsadm
/usr/bin/ipvsadm-restore
/usr/bin/ipvsadm-save

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ipvsadm/*
