#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipvsadm
Version  : 1.29
Release  : 3
URL      : https://mirrors.edge.kernel.org/pub/linux/utils/kernel/ipvsadm/ipvsadm-1.29.tar.xz
Source0  : https://mirrors.edge.kernel.org/pub/linux/utils/kernel/ipvsadm/ipvsadm-1.29.tar.xz
Summary  : Utility to administer the Linux Virtual Server
Group    : Development/Tools
License  : GPL-2.0
Requires: ipvsadm-bin = %{version}-%{release}
Requires: ipvsadm-license = %{version}-%{release}
Requires: ipvsadm-man = %{version}-%{release}
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : popt-dev

%description
ipvsadm is a utility to administer the IP Virtual Server services
offered by the latest Linux kernel 2.6.x.

%package bin
Summary: bin components for the ipvsadm package.
Group: Binaries
Requires: ipvsadm-license = %{version}-%{release}
Requires: ipvsadm-man = %{version}-%{release}

%description bin
bin components for the ipvsadm package.


%package license
Summary: license components for the ipvsadm package.
Group: Default

%description license
license components for the ipvsadm package.


%package man
Summary: man components for the ipvsadm package.
Group: Default

%description man
man components for the ipvsadm package.


%prep
%setup -q -n ipvsadm-1.29

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543601570
make

%install
export SOURCE_DATE_EPOCH=1543601570
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipvsadm
cp debian/copyright %{buildroot}/usr/share/package-licenses/ipvsadm/debian_copyright
%make_install
## install_append content
mkdir -p %{buildroot}/usr/share
mv %{buildroot}/usr/man %{buildroot}/usr/share/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ipvsadm
/usr/bin/ipvsadm-restore
/usr/bin/ipvsadm-save

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ipvsadm/debian_copyright

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/ipvsadm-restore.8
/usr/share/man/man8/ipvsadm-save.8
/usr/share/man/man8/ipvsadm.8
